tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: dbt_dev
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
      threads: 8
      query_tag: tasty_bytes_dbt_poc_dev
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: dbt_deployer
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh
      threads: 8
      query_tag: tasty_bytes_dbt_poc_prod
